repository: 'sysartifacts/sysartifacts.github.io'
url: "https://sysartifacts.github.io"
markdown: kramdown
plugins:
- jekyll-redirect-from # see https://docs.github.com/en/enterprise/2.13/user/articles/redirects-on-github-pages
exclude:
- Gemfile
- Gemfile.lock

# variables, accessible via site.xxx in the templates
# NB: --watch will not pick up changes here, so jekyll must be restarted
name: Artifacts Evaluation # Can we find a better name?
